manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infusedkim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: infusedkim
      revision: my-changes/split-encoder
      import: app/west.yml
  self:
    path: config
